### PR TITLE
Add user_dec DeliveryReceipt type

### PR DESCRIPTION
**Pull request by dbrgn**
Sent when a user declines a message. The type was still missing.

### CODE REVIEW

**Comment by lgrahl** [comment]
Could you rebase the PR onto the `develop` branch? We should also change the names to `user_acknowledge` and `user_decline`.

**Comment by dbrgn** [comment]
Can do. It's a breaking change though, and one that won't even be noticed at runtime if people use `message.receipt_type.name`.

**Comment by lgrahl** [comment]
Good point, then we should have a `user_ack` attribute as well and make it deprecated.

**Review by lgrahl — CHANGES_REQUESTED** [review]
See https://github.com/lgrahl/threema-msgapi-sdk-python/pull/25#issuecomment-263060699

**Comment by lgrahl** [comment]
PR-build passes - all I need.

**Pull request merged**
