### PR TITLE
Added rudimentary group message support

### PR DESCRIPTION
**Pull request by maltefiala**
Decoding group text messages working.
All other group directives return "None".

### CODE REVIEW

**Comment by lgrahl** [comment]
I don't want to add official support for group messages as long as there is no official support by Threema. Of course, you are free to just derive from `threema.gateway.e2e.Message` and its subclasses to implement group messages (or keep the fork).

Additonally, adding (general) group support would require more than just a `group` keyword to the `Message` subclasses because at least some of them have different structures and behave differently.

I will poke the guys at Threema and let them know that there seems to be a demand for this feature.

**Comment by maltefiala** [comment]
Hej @lgrahl :
Yes, it's rudimentary. However, I tested the group messages quite thoroughly (sent about 100 messages so far) and would deem the group text message decryption stable. As all other group directives don't work yet, I did not see the need for a GroupMessage class so far.

Poking the threema guys would be great. Something else: Do you plan on releasing an image message decryption support soon? If not, I will start implementing this the following weeks.

**Comment by lgrahl** [comment]
Let's continue the decryption discussion in #15.

**Comment by lgrahl** [comment]
I've asked Threema about this matter. Group messages are not supported.

**Pull request closed without merging**
